MVCProductsChallenge.UI/Controllers/ProductTypeController.cs
using MVCProductsChallenge.Model.Entities;
using MVCProductsChallenge.Services;
using MVCProductsChallenge.UI.Helpers;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace MVCProductsChallenge.UI.Controllers
{
    public class ProductTypeController : Controller
    {
        private readonly IProductTypeService _productTypeService;

        public ProductTypeController()
        {
            _productTypeService = new ProductTypeService();
        }

        public ActionResult Index()
        {
            ViewBag.ProductTypes = _productTypeService
                .List()
                .OrderBy(x => x.Name)
                .ToList();

            return View();
        }

        public ActionResult CreateProductType() => View(new ProductType());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitCreateProductType([Bind(Include = "Name")] ProductType productType)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _productTypeService.Create(productType);
                    TempData["Message"] = MessageHelpers.GetSuccessMessage($"Product type '{productType.Name}' was added successfully");
                    return RedirectToAction("Index");
                }

                return View("CreateProductType", productType);
            }
            catch (Exception ex)
            {
                TempData["Message"] = MessageHelpers.GetExceptionMessage(ex);
                return View("CreateProductType", productType);
            }
        }

        public ActionResult EditProductType(int? productTypeId)
        {
            if (productTypeId == null)
                return RedirectToAction("Index");

            var selectedProductType = _productTypeService.Get((int)productTypeId);

            if (selectedProductType == null)
                return RedirectToAction("Index");

            return View("EditProductType", selectedProductType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitEditProductType([Bind(Include = "Id,Name")] ProductType productType)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var oldProductType = _productTypeService.Get(productType.Id);
                    _productTypeService.Update(oldProductType, productType);
                    TempData["Message"] = MessageHelpers.GetSuccessMessage($"Product type '{productType.Name}' was edited successfully");
                    return RedirectToAction("Index");
                }

                return View("EditProductType", productType);
            }
            catch (Exception ex)
            {
                TempData["Message"] = MessageHelpers.GetExceptionMessage(ex);
                return View("EditProductType", productType);
            }
        }

        public ActionResult DeleteProductType(int? productTypeId)
        {
            if (productTypeId == null)
                return RedirectToAction("Index");

            var selectedProductType = _productTypeService
                .List()
                .Where(x => x.Id == productTypeId)
                .Include(x => x.Products)
                .FirstOrDefault();

            if (selectedProductType == null)
                return RedirectToAction("Index");

            return View("DeleteProductType", selectedProductType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitDeleteProductType(ProductType productType)
        {
            try
            {
                //check
                _productTypeService.Delete(productType);
                TempData["Message"] = MessageHelpers.GetSuccessMessage($"Product name '{productType.Name}' was deleted successfully");
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["Message"] = MessageHelpers.GetExceptionMessage(ex);
                return View("DeleteProductType", productType);
            }
        }
    }
}

MVCProductsChallenge.UI/Views/ProductType/CreateProductType.cshtml
@model ProductType

@{
    ViewBag.Title = "Create product type";
}

@Html.Partial("_MessageRenderer")

<div class="row mb-3">
    <button type="button" id="backButton" class="btn btn-primary" data-url="@Url.Action("Index", "ProductType")">
        Go back
    </button>
</div>

@using (var form = Html.BeginForm("SubmitCreateProductType", "ProductType", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Save changes" />
        <input type="reset" value="Reset values" class="btn btn-secondary" />
    </div>
}

@section scripts{
    <script src="~/Scripts/app/go-back.js"></script>
}

MVCProductsChallenge.UI/Views/ProductType/DeleteProductType.cshtml
@model ProductType
@{
    ViewBag.Title = $"Delete product type ({Model.Name})";
}

@Html.Partial("_MessageRenderer")

@if (Model.Products.Count == 0)
{
    <h2>Do you want to delete this product?</h2>

    using (var form = Html.BeginForm("SubmitDeleteProductType", "ProductType", FormMethod.Post))
    {
        Html.AntiForgeryToken();
        Html.HiddenFor(model => model.Id);
        Html.HiddenFor(model => model.Name);

        <div class="row">
            <input type="submit" class="btn btn-danger mr-1" value="Delete product type" />
            <button type="button" id="backButton" class="btn btn-primary ml-1" data-url="@Url.Action("Index", "ProductType")">
                Go back
            </button>
        </div>
    }
}
else
{
    <p>You cannot delete this product type because it has products related. Please delete all @Model.Name products to delete this product type.</p>

    <button type="button" id="backButton" class="btn btn-primary" data-url="@Url.Action("Index", "ProductType")">
        Go back
    </button>
}

@section scripts{
    <script src="~/Scripts/app/go-back.js"></script>
}

MVCProductsChallenge.UI/Views/ProductType/EditProductType.cshtml
@model ProductType

@{
    ViewBag.Title = $"Edit product type ({Model.Name})";
}

@Html.Partial("_MessageRenderer")

<div class="row mb-3">
    <button type="button" id="backButton" class="btn btn-primary" data-url="@Url.Action("Index", "ProductType")">
        Go back
    </button>
</div>

@using (var form = Html.BeginForm("SubmitEditProductType", "ProductType", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-warning" value="Update changes" />
    </div>
}

@section scripts{
    <script src="~/Scripts/app/go-back.js"></script>
}

MVCProductsChallenge.UI/Views/ProductType/Index.cshtml
@{
    ViewBag.Title = "Product types";
}

@Html.Partial("_MessageRenderer")

<div class="row mb-5">
    <div class="col">
        <button type="button" id="addProductTypeButton" class="btn btn-primary" data-url="@Url.Action("CreateProductType", "ProductType")">
            Add product type <span class="fa fa-plus"></span>
        </button>
    </div>
</div>

@Html.Partial("_ProductTypesTable", (IList<ProductType>)ViewBag.ProductTypes)

@section scripts{
    <script src="~/Scripts/app/product-type/index.js"></script>
}

MVCProductsChallenge.UI/Views/ProductType/ProductTypeRow.cshtml
@model ProductType
@{
    string editUrl = @Url.Action("EditProductType", "ProductType") + "?productTypeId=" + Model.Id.ToString();
}

<tr>
    <td>@Model.Name</td>
    <td>
        <button type="button" class="btn btn-warning update" title="Edit" data-url="@editUrl">
            <span class="fa fa-pencil"></span>
        </button>
    </td>
</tr>

MVCProductsChallenge.UI/Views/ProductType/ProductTypesTable.cshtml
@model IList<ProductType>

<table id="productTypesTable" class="table table-striped table-responsive-md">
    <thead>
        <tr>
            <th>Name</th>
            <th>Edit</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count > 0)
        {
            foreach (var product in Model)
            {
                @Html.Partial("ProductTypeRow", product)
            }
        }
        else
        {
            <tr>
                <td colspan="2" class="text-center">
                    <em>There are no product types to show</em>
                </td>
            </tr>
        }
    </tbody>
</table>

MVCProductsChallenge.UI/Views/ProductType/_ProductTypeRow.cshtml
@model ProductType
@{
    string editUrl = @Url.Action("EditProductType", "ProductType") + "?productTypeId=" + Model.Id.ToString(),
        deleteUrl = @Url.Action("DeleteProductType", "ProductType") + "?productTypeId=" + Model.Id.ToString();;
}

<tr>
    <td>@Model.Name</td>
    <td>
        <button type="button" class="btn btn-warning update" title="Edit" data-url="@editUrl">
            <span class="fa fa-pencil"></span>
        </button>
    </td>
    <td>
        <button type="button" class="btn btn-danger delete" title="Delete" data-url="@deleteUrl">
            <span class="fa fa-trash"></span>
        </button>
    </td>
</tr>

MVCProductsChallenge.UI/Views/ProductType/_ProductTypesTable.cshtml
@model IList<ProductType>

<table id="productTypesTable" class="table table-striped table-responsive-md">
    <thead>
        <tr>
            <th>Name</th>
            <th>Edit</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count > 0)
        {
            foreach (var product in Model)
            {
                @Html.Partial("_ProductTypeRow", product)
            }
        }
        else
        {
            <tr>
                <td colspan="2" class="text-center">
                    <em>There are no product types to show</em>
                </td>
            </tr>
        }
    </tbody>
</table>